### ISSUE TITLE
Pass access error when running demo scene

### ISSUE THREAD

**Issue by aandnota** [playdeadgames/temporal#2] opened 2016-03-26 16:36 UTC
I get this error when I run the demo scene:

```
Trying to access pass 1, but material 'Playdead/Post/VelocityBuffer' subshader (0) has only 1 valid passes.
UnityEngine.Material:SetPass(Int32)
```

I've edited the shader files to account for glcore.

Unity 5.4.3f1 on OSX 10.11.3

**Comment by yvan-sraka** [comment] 2017-01-07 17:02
Hello,

Looks like this issue is a duplicate of: https://github.com/playdeadgames/temporal/issues/1

**Closed as completed** 2017-03-17 14:50 UTC
